[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.8.17"

[[constraint]]
  name = "github.com/republicprotocol/republic-go"
  branch = "develop"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

# Fix to resolve dependency issues within go-ethereum
[[override]]
  name = "gopkg.in/fatih/set.v0"
  version = "=0.1.0"

[prune]
  go-tests = true